name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        resources:
          limits:
            memory: 2g
            cpus: '2.0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv movie_env
        source movie_env/bin/activate
        pip install --upgrade pip
        pip install -r movie_ai/requirements.txt
        pip install coverage

    - name: Wait for MongoDB to be ready
      run: |
        until mongo --eval 'db.runCommand({ ping: 1 })'; do
          echo "Waiting for MongoDB to start..."
          sleep 5
        done

    - name: Import MongoDB data
      run: |
        sleep 10
        mongoimport --db moviedb --collection scenes --file movie_ai/data/scenes.json --type json

    - name: Run tests with coverage
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        source movie_env/bin/activate
        cd movie_ai
        coverage run --branch --source='.' manage.py test movieapi

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: movie_ai/htmlcov
