name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv movie_env
        source movie_env/bin/activate
        pip install --upgrade pip
        pip install -r movie_ai/requirements.txt
        pip install coverage

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '6.0'

    - name: Wait for MongoDB to be ready
      run: |
        for i in {1..30}; do
          if mongo --eval 'db.runCommand({ ping: 1 })'; then
            echo "MongoDB is ready!"
            break
          fi
          echo "Waiting for MongoDB to start..."
          sleep 5
        done

    - name: Import MongoDB data
      run: |
        sleep 10
        mongoimport --db moviedb --collection scenes --file movie_ai/data/scenes.json --type json

    - name: Run tests with coverage
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        source movie_env/bin/activate
        cd movie_ai
        coverage run --branch --source='.' manage.py test movieapi

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: movie_ai/htmlcov
